spring:
  application:
    name:
  profiles:
    active: local # default로는 local이 실행되도록한다.

  config:
    import:
      - logging.yml
      - db.yml

slack-api:
  notify-channel-id: C06015L3JTY

---
spring:
  config:
    activate:
      on-profile: local

---
spring:
  config:
    activate:
      on-profile: prod
